server.port: 8080
spring.profiles: default
teamo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://teamolab.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus